### ISSUE TITLE
Not able to add question

### ISSUE THREAD

**Issue by rohitagarwal88** [zoonk/web#15]
**Describe the bug**
When I was creating a question on zoonk.org and tried to submit the question. It threw the 
**Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field createdBy.facebook)**

**To Reproduce**
1. Go to 'https://en.zoonk.org/posts/add'
2. Fill in title, content and select topic
3. Scroll down and click on save.

**Expected behavior**
The question should be submitted.

**Screenshots**
<img width="1536" alt="Screenshot 2020-05-26 at 5 22 04 PM" src="https://user-images.githubusercontent.com/890915/82898215-7ff5e480-9f76-11ea-80b0-7cf570439ed8.png">

**Desktop (please complete the following information):**
 - OS: [Mac 10.15.4]
 - Browser [ chrome Version 81.0.4044.138 (Official Build) (64-bit)]

**Additional context**

**Comment by wceolin** [comment]
Thanks for reporting this issue, @rohitagarwal88. I'm having a look at it.

**Comment by wceolin** [comment]
Hi @rohitagarwal88! A bug fix for this was deployed. It should be working now. Thanks again for reporting this issue. 😃
