### ISSUE TITLE
Comment or Question like count issue

### ISSUE THREAD

**Issue by rohitagarwal88** [zoonk/web#17]
**Describe the bug**
Click on the comment or Question like button multiple and check the issue. See this screen recording for the issue
https://drive.google.com/file/d/1XrtA1I3AKptprFUlTRM7_TAvX-FawxSS/view?usp=sharing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any question'
2. Click on 'like button multiple times'

**Expected behaviour**
Like button should get disabled after like/unlike or there should be throttling of response to avoid multiple API calls.

**Screenshots**
https://drive.google.com/file/d/1XrtA1I3AKptprFUlTRM7_TAvX-FawxSS/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [Mac ]
 - Browser [Chrome
 - Version [81]

**Comment by wceolin** [comment]
Thanks for reporting this!

**Comment by wceolin** [comment]
@rohitagarwal88 A fix for this bug was just released in the latest version. :)
